services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mannabe
      POSTGRES_PASSWORD: mannabe
      POSTGRES_DB: mannabe
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
